# Generated by Django 3.2.7 on 2021-10-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('postID', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
