# Generated by Django 3.2.7 on 2021-11-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('CommentServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
