# Generated by Django 3.2.7 on 2021-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('LikeServiceApp', '0003_auto_20211011_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='name',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
