# Generated by Django 3.2.7 on 2021-11-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PostServiceApp', '0002_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
